POST http://localhost:3000/auth/login
Content-type: application/json

{
  "username": "john",
  "password": "changeme"
}

###
GET http://localhost:3000/auth/profile
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJzdWIiOjEsInNjb3BlIjpbInVzZXJzOnVwZGF0ZSIsImFpcnBvcnRzOmxpc3QiLCJmbGlnaHRzOmNyZWF0ZSJdLCJpYXQiOjE3MjE2NTg5MjgsImV4cCI6MTcyMTY1ODk4OH0.OIqZ7I6mvAOMIP2nswQecwv4I06KhM9PhRAPrJNHm2w

###
GET http://localhost:3000/airports
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJzdWIiOjEsInNjb3BlIjpbInVzZXJzOnVwZGF0ZSIsImFpcnBvcnRzOmxpc3QiLCJmbGlnaHRzOmNyZWF0ZSJdLCJpYXQiOjE3MjE2NTk1MDYsImV4cCI6MTcyMTY1OTU2Nn0.mD96K3wko7MPIQqf8CaqSGaPh-3PpEp4jCCSiq7Gsxc
